name = "edgeshop"
main = "worker/src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[triggers]
crons = ["0 * * * *"]
