name = "edgeshop"
main = "worker/src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "frontend/dist"
binding = "ASSETS"

[triggers]
crons = ["0 * * * *"]
